language: node_js
node_js:
- stable
- '6'
- '4'
notifications:
  slack:
    secure: Y7N9ZnEMg8dr+IGIwO/vsTBq4R3UAine6L5HVQupKqZm7cCz6YssimTrQG8K0NlIl61F9ILh8iNh20mcE0HpugTULd0ecs6wtEh3yzOebxQ1q1F598i6lFWFiMTjLjWUxIcEwYF+mbXIhAYv0pDczo+/2CTXHRVbDZMTwIe+da8aOy2+oxWLbyqcaqTLOBR5Dm4hPodofW8RyaP74ouLEON049AOt+iRDrXZl0nP25crAbCA45gQ01aSYVktNOd3aeMjG3AGgz6Wndu/i8g0DYJXqSzjeqBCdAeBDwo/YR7BZLjoa1dOgYWeKUjU+DWv2gxa/OJ7GdNEt2exKdS9UnAi1sju4UvjN9shoGIHZbsyvholMP3jmSPeXCwqi6L7cWnwLaa1ktPntGmS3NhGcgnniYaTwJNNDY3CrCYhWcpDq+kjWroXQ22dkVki2FEeRon+p8d6Lp++tAAE53Vv6RS1aBH8hNpSlRFQNvZzimu1uxgX5oY7tdpJ6x0OKNnAJ0/tRw0GWJHJw0wOFJvTATOndxwgoYftj32e0M+2g31aIB5PPF9707vjNVnBU9XyTV6lNEsSiLiqk66xuKyVHIg6I6sVsVd70eDBvBZfaR0TMjqtFabhWJdH1gy6IQvGJyrkTO337kYiqSwj1ikqZ7nBKxcx4zrxJSYSQFuzqLo=
